// Devocionales diarios. El texto bíblico se toma de rv1909.json según la referencia
// b = número de libro (1-66), c = capítulo, v = [versículo inicial, final]
// quitar = encabezado del salmo que viene pegado al versículo 1 en los datos
export const DEVOCIONALES = [
  { b:19, c:23,  v:[1,3],   quitar:"Salmo de David. ", tema:"Él me guía",
    reflexion:"Un pastor no deja solas a sus ovejas ni les pide que encuentren el camino por su cuenta. Hoy puedes descansar en que Dios conoce tu ruta mejor que tú.",
    pregunta:"¿En qué área necesitas dejar que Dios te guíe hoy?" },
  { b:6,  c:1,   v:[9,9],   tema:"Valentía",
    reflexion:"Dios no prometió ausencia de retos, sino su presencia en medio de ellos. El valor cristiano nace de saber con quién caminas.",
    pregunta:"¿Qué decisión estás posponiendo por miedo? Preséntasela a Dios." },
  { b:20, c:3,   v:[5,6],   tema:"Confiar",
    reflexion:"Confiar de todo corazón es soltar el control de lo que no entendemos. Él endereza lo que nosotros todavía no vemos.",
    pregunta:"¿Qué situación necesitas entregarle hoy sin entenderla del todo?" },
  { b:23, c:41,  v:[10,10], tema:"No temas",
    reflexion:"El temor se calma cuando recordamos quién nos sostiene. La promesa no es que no habrá tormentas, sino que Él está contigo en ellas.",
    pregunta:"¿Qué temor quieres poner hoy en sus manos?" },
  { b:40, c:6,   v:[33,33], tema:"Prioridades",
    reflexion:"Buscar primero el reino ordena todo lo demás. Cuando Dios ocupa el primer lugar, lo urgente deja de mandar sobre ti.",
    pregunta:"¿Qué ocupa hoy el primer lugar en tu corazón?" },
  { b:43, c:3,   v:[16,16], tema:"Un amor que se entrega",
    reflexion:"Dios no amó solo con palabras: dio lo más valioso que tenía. Ese amor te alcanza tal como estás hoy.",
    pregunta:"¿Cómo puedes responder hoy a ese amor?" },
  { b:45, c:8,   v:[28,28], tema:"Dios obra",
    reflexion:"No dice que todo lo que pasa sea bueno, sino que Dios trabaja en todo para el bien de quienes le aman. Nada se desperdicia en sus manos.",
    pregunta:"¿Qué situación difícil necesitas mirar hoy con ojos de fe?" },
  { b:50, c:4,   v:[6,7],   tema:"Paz en lugar de afán",
    reflexion:"La oración es el camino para cambiar la preocupación por paz. Presenta tus peticiones con gratitud y deja que su paz cuide tu corazón.",
    pregunta:"¿Qué preocupación vas a convertir hoy en oración?" },
  { b:19, c:46,  v:[1,2],   quitar:"Al Músico principal: de los hijos de Coré: Salmo sobre Alamoth. ", tema:"Nuestro refugio",
    reflexion:"Cuando todo se mueve, Dios permanece. Él es amparo y ayuda presente, no lejana.",
    pregunta:"¿A dónde corres primero cuando llegan los problemas?" },
  { b:24, c:29,  v:[11,11], tema:"Pensamientos de paz",
    reflexion:"Dios piensa en ti con propósito y esperanza, incluso en las temporadas de espera. Su plan es mayor que tu momento actual.",
    pregunta:"¿Qué esperanza quieres renovar hoy?" },
  { b:40, c:11,  v:[28,29], tema:"Descanso para el alma",
    reflexion:"Jesús invita a los cansados, no a los que ya lo tienen todo resuelto. Su yugo es ligero porque Él lo lleva contigo.",
    pregunta:"¿Qué carga necesitas dejar hoy a sus pies?" },
  { b:43, c:14,  v:[27,27], tema:"Su paz",
    reflexion:"La paz de Jesús no depende de las circunstancias. Él la da de una manera que el mundo no puede dar.",
    pregunta:"¿En qué parte de tu vida necesitas hoy su paz?" },
  { b:19, c:119, v:[105,105], quitar:"NUN. ", tema:"Una lámpara en el camino",
    reflexion:"La Palabra no siempre ilumina todo el camino, pero sí el siguiente paso. Basta con caminar a su luz.",
    pregunta:"¿Qué paso te está mostrando Dios hoy?" },
  { b:48, c:5,   v:[22,23], tema:"El fruto del Espíritu",
    reflexion:"El fruto no se fabrica: se cultiva permaneciendo cerca de Dios. Pídele que crezca en ti lo que todavía te falta.",
    pregunta:"¿Qué fruto necesitas que crezca más en ti?" },
  { b:58, c:11,  v:[1,1],   tema:"Fe",
    reflexion:"La fe es confiar en lo que todavía no se ve, porque conocemos a quien lo prometió.",
    pregunta:"¿Qué promesa de Dios quieres creer hoy?" },
  { b:60, c:5,   v:[7,7],   tema:"Echar la carga",
    reflexion:"A Dios no le cansan tus preocupaciones: le importas de verdad. Entregarle la ansiedad es un acto de confianza.",
    pregunta:"¿Qué ansiedad vas a entregarle ahora mismo?" },
  { b:19, c:27,  v:[1,1],   quitar:"Salmo de David. ", tema:"Luz y salvación",
    reflexion:"Si Dios es tu luz y tu fortaleza, el miedo pierde su poder sobre ti.",
    pregunta:"¿En qué situación necesitas luz hoy?" },
  { b:45, c:12,  v:[1,2],   tema:"Una mente renovada",
    reflexion:"Adorar también es entregarle la vida diaria. Dios transforma desde adentro, renovando nuestra manera de pensar.",
    pregunta:"¿Qué pensamiento necesita ser renovado hoy por su Palabra?" },
  { b:59, c:1,   v:[5,5],   tema:"Sabiduría",
    reflexion:"Dios da sabiduría con generosidad a quien se la pide. No hace falta tener todas las respuestas, solo pedirlas.",
    pregunta:"¿Qué decisión necesita hoy la sabiduría de Dios?" },
  { b:25, c:3,   v:[22,23], tema:"Misericordias nuevas",
    reflexion:"Cada mañana trae misericordias nuevas, aunque ayer haya sido difícil. Su fidelidad no se agota.",
    pregunta:"¿Qué necesitas dejar atrás para recibir su misericordia hoy?" },
  { b:19, c:139, v:[23,24], tema:"Examíname, Señor",
    reflexion:"Una oración honesta le pide a Dios que muestre lo que hay en el corazón. Su luz corrige para guiar, no para condenar.",
    pregunta:"¿Qué quiere mostrarte Dios hoy sobre tu corazón?" },
  { b:40, c:5,   v:[14,16], tema:"Luz del mundo",
    reflexion:"Tu vida es un testimonio. Las buenas obras hechas con humildad llevan a otros a honrar a Dios.",
    pregunta:"¿A quién puedes servir hoy como luz?" },
  { b:51, c:3,   v:[23,23], tema:"Trabajar para el Señor",
    reflexion:"Todo trabajo adquiere propósito cuando se hace como para Dios. Hasta lo más pequeño puede ser adoración.",
    pregunta:"¿Cómo puedes hacer tu tarea de hoy como para el Señor?" },
  { b:19, c:37,  v:[4,5],   tema:"Deleitarse en Dios",
    reflexion:"Cuando Dios es tu mayor gozo, tus deseos se ordenan. Encomendarle el camino es confiar en que Él actuará.",
    pregunta:"¿Qué camino necesitas encomendarle hoy?" },
  { b:23, c:40,  v:[31,31], tema:"Fuerzas renovadas",
    reflexion:"Esperar en Dios no es pasividad: es confiar y recibir fuerzas nuevas. Él levanta a los cansados.",
    pregunta:"¿En qué área necesitas hoy nuevas fuerzas?" },
  { b:62, c:4,   v:[19,19], tema:"Amamos porque Él nos amó",
    reflexion:"Nuestro amor es una respuesta al suyo. Quien se sabe amado puede amar con libertad.",
    pregunta:"¿A quién necesitas amar hoy como Dios te ama?" },
  { b:49, c:2,   v:[8,9],   tema:"Por gracia",
    reflexion:"La salvación es un regalo, no un premio. Descansar en la gracia es dejar de intentar ganarse el amor de Dios.",
    pregunta:"¿Dónde necesitas recordar hoy que todo es por gracia?" },
  { b:19, c:91,  v:[1,2],   tema:"Bajo su sombra",
    reflexion:"Habitar en Dios es vivir cerca de Él cada día. Su sombra protege a quien se refugia en Él.",
    pregunta:"¿Cómo puedes estar más cerca de Dios hoy?" },
  { b:47, c:12,  v:[9,9],   tema:"Poder en la debilidad",
    reflexion:"Su gracia basta incluso cuando te sientes sin fuerzas. Su poder se perfecciona justo donde tú no llegas.",
    pregunta:"¿En qué debilidad necesitas hoy su gracia?" },
  { b:66, c:3,   v:[20,20], tema:"A la puerta",
    reflexion:"Jesús llama y espera: no entra a la fuerza. Abrirle la puerta es invitarlo a tu intimidad diaria.",
    pregunta:"¿Qué área de tu vida quieres abrirle hoy?" },
  { b:43, c:15,  v:[5,5],   tema:"Permanecer en Él",
    reflexion:"Separados de Jesús nada podemos; unidos a Él, damos fruto. La intimidad con Dios es la fuente de todo lo demás.",
    pregunta:"¿Qué te ayuda a permanecer cerca de Él?" },
];

export function devocionalDeHoy(d = new Date()) {
  const start = Date.UTC(d.getFullYear(), 0, 0);
  const cur = Date.UTC(d.getFullYear(), d.getMonth(), d.getDate());
  const doy = Math.floor((cur - start) / 86400000);
  return DEVOCIONALES[doy % DEVOCIONALES.length];
}
