// Estudios bíblicos incluidos. Ningún pasaje se repite entre estudios
// ni con los versículos de los devocionales diarios.
// Cada día: pasaje (b = libro 1-66, c = capítulo, v1-v2 = versículos), idea guía y preguntas.
export const ESTUDIOS = [
  {
    id: "fe-inicial", builtin: true,
    title: "Primeros pasos en la fe",
    description: "Siete días para conocer a Jesús, el amor del Padre y la vida en comunidad.",
    days: [
      { titulo:"El Verbo hecho carne", b:43, c:1, v1:1, v2:14,
        idea:"Juan presenta a Jesús como la Palabra eterna que se hizo humano para mostrarnos al Padre.",
        preguntas:["¿Qué dice este pasaje sobre quién es Jesús?","¿Qué significa para ti que Dios haya vivido entre nosotros?"] },
      { titulo:"El Padre que espera", b:42, c:15, v1:11, v2:24,
        idea:"Jesús cuenta cómo el padre corre a recibir al hijo que regresa: así es el corazón de Dios con quien vuelve a Él.",
        preguntas:["¿Qué hace el padre antes de que el hijo termine de hablar?","¿Hay algo que te impide volver a Dios con confianza?","¿Te identificas más con el hijo menor, el mayor o el padre?"] },
      { titulo:"Paz con Dios", b:45, c:5, v1:1, v2:8,
        idea:"Pablo explica que, por la fe en Cristo, ya no somos enemigos de Dios sino amigos con paz.",
        preguntas:["¿Qué recibe el creyente según los primeros versículos?","¿Cómo demuestra Dios su amor, según el versículo 8?"] },
      { titulo:"El buen pastor", b:43, c:10, v1:1, v2:11,
        idea:"Jesús se presenta como la puerta y el pastor: conoce a sus ovejas, las cuida y da su vida por ellas.",
        preguntas:["¿Qué hace el pastor que el extraño no hace?","¿Qué voz estás escuchando con más atención últimamente?"] },
      { titulo:"La vida en comunidad", b:44, c:2, v1:42, v2:47,
        idea:"La primera iglesia perseveraba junta en la enseñanza, la comunión, el partimiento del pan y la oración.",
        preguntas:["¿Qué cosas hacía la iglesia primitiva según el versículo 42?","¿Cuál de ellas necesitas fortalecer en tu vida?","¿Cómo puedes apoyar a alguien de tu iglesia esta semana?"] },
      { titulo:"La gran comisión", b:40, c:28, v1:16, v2:20,
        idea:"Jesús envía a sus discípulos a hacer discípulos en todas las naciones y promete estar con ellos siempre.",
        preguntas:["¿Qué ordena Jesús y qué promete al final?","¿A quién puedes hablarle de Jesús esta semana?"] },
      { titulo:"Caminar en la luz", b:62, c:1, v1:5, v2:10,
        idea:"Juan enseña que caminar en la luz implica honestidad con Dios, confesión y comunión con otros.",
        preguntas:["¿Qué promete Dios a quien confiesa sus pecados?","¿Qué necesitas confesarle hoy a Dios?"] },
    ],
  },
  {
    id: "sermon-monte", builtin: true,
    title: "El carácter de Cristo",
    description: "Seis días en el Sermón del Monte para vivir como discípulo de Jesús.",
    days: [
      { titulo:"Los de corazón humilde", b:40, c:5, v1:1, v2:12,
        idea:"Jesús abre su sermón mostrando que la bendición de Dios llega a los humildes, los misericordiosos y los que tienen hambre de justicia.",
        preguntas:["¿Cuál de estas actitudes te cuesta más y por qué?","¿Qué promesa de este pasaje te llama más la atención?"] },
      { titulo:"Amar a los enemigos", b:40, c:5, v1:38, v2:48,
        idea:"Jesús lleva el amor más allá de lo cómodo: pide amar y orar incluso por quien nos hace mal.",
        preguntas:["¿A quién te cuesta perdonar o amar?","¿Qué paso concreto puedes dar hoy hacia esa persona, aunque sea orar por ella?"] },
      { titulo:"Dar en secreto", b:40, c:6, v1:1, v2:8,
        idea:"Dios mira el corazón: las obras de generosidad no son para ser vistos, sino para agradar al Padre.",
        preguntas:["¿Qué motivación hay detrás de lo que haces por otros?","¿Cómo puedes servir hoy sin esperar reconocimiento?"] },
      { titulo:"Cómo orar", b:40, c:6, v1:9, v2:15,
        idea:"Jesús enseña un modelo de oración que comienza por el Padre, su nombre y su reino, antes de nuestras necesidades.",
        preguntas:["¿Qué orden sigue esta oración?","¿Qué parte de este modelo sueles olvidar al orar?","¿Qué dice Jesús sobre el perdón?"] },
      { titulo:"Dónde está tu tesoro", b:40, c:6, v1:19, v2:24,
        idea:"Jesús invita a poner el corazón en tesoros eternos y a servir a un solo Señor.",
        preguntas:["¿Dónde está tu tesoro hoy?","¿Qué cambiaría si vivieras con una visión más eterna?"] },
      { titulo:"La casa sobre la roca", b:40, c:7, v1:24, v2:29,
        idea:"La diferencia entre las dos casas no es oír, sino obedecer lo que Jesús enseña.",
        preguntas:["¿Qué enseñanza de Jesús necesitas poner en práctica esta semana?","¿Qué tormenta está poniendo a prueba tu fundamento?"] },
    ],
  },
  {
    id: "oracion", builtin: true,
    title: "Oración y comunión con Dios",
    description: "Cinco días para aprender a orar con confianza, constancia y gratitud.",
    days: [
      { titulo:"Pedid, buscad, llamad", b:42, c:11, v1:5, v2:13,
        idea:"Jesús anima a orar con insistencia, porque el Padre da cosas buenas a sus hijos.",
        preguntas:["¿Qué tres verbos usa Jesús para describir la oración?","¿Qué te hace dudar de que Dios te escucha?"] },
      { titulo:"Orar sin desmayar", b:42, c:18, v1:1, v2:8,
        idea:"La parábola de la viuda enseña a no rendirse en la oración.",
        preguntas:["¿Qué hace la viuda para conseguir lo que pide?","¿Qué petición has dejado de presentar a Dios?"] },
      { titulo:"Una vida de gratitud", b:52, c:5, v1:16, v2:24,
        idea:"Pablo resume la vida cristiana en hábitos sencillos: gozo, oración constante y gratitud en todo.",
        preguntas:["¿Cuál de estos hábitos te resulta más difícil?","¿Por qué puedes dar gracias hoy?"] },
      { titulo:"Acercarse con confianza", b:58, c:4, v1:14, v2:16,
        idea:"Tenemos un sumo sacerdote que entiende nuestra debilidad, por eso podemos acercarnos al trono de la gracia.",
        preguntas:["¿Qué recibimos al acercarnos con confianza?","¿Qué te hace sentir lejos de Dios y cómo puedes superarlo?"] },
      { titulo:"La oración de fe", b:59, c:5, v1:13, v2:18,
        idea:"Santiago anima a orar en toda circunstancia, en el sufrimiento y en la alegría, y a orar unos por otros.",
        preguntas:["¿Por quién puedes orar hoy?","¿Qué enseña el ejemplo de Elías sobre la oración?"] },
    ],
  },
  {
    id: "vida-espiritu", builtin: true,
    title: "Vida en el Espíritu",
    description: "Seis días para conocer la obra del Espíritu Santo en el creyente y en la iglesia.",
    days: [
      { titulo:"Sin condenación", b:45, c:8, v1:1, v2:11,
        idea:"Pablo muestra que quien está en Cristo vive según el Espíritu, con vida y paz.",
        preguntas:["¿Qué diferencia hay entre vivir según la carne y según el Espíritu?","¿Qué área de tu vida necesitas rendir al Espíritu?"] },
      { titulo:"Andar en el Espíritu", b:48, c:5, v1:16, v2:21,
        idea:"Pablo contrasta las obras de la carne con la vida guiada por el Espíritu.",
        preguntas:["¿Qué luchas reconoces en tu vida?","¿Cómo puedes caminar hoy más cerca del Espíritu?"] },
      { titulo:"El día de Pentecostés", b:44, c:2, v1:1, v2:13,
        idea:"El Espíritu Santo descendió sobre los discípulos y cada uno oyó las maravillas de Dios en su propio idioma.",
        preguntas:["¿Qué ocurrió cuando llegó el Espíritu?","¿Qué anhelas que haga el Espíritu en tu iglesia hoy?"] },
      { titulo:"Dones para servir", b:46, c:12, v1:1, v2:11,
        idea:"Hay diversidad de dones, pero un mismo Espíritu, y se dan para el bien común.",
        preguntas:["¿Qué dones menciona el pasaje?","¿Cómo puedes poner tus dones al servicio de otros?"] },
      { titulo:"El camino del amor", b:46, c:13, v1:1, v2:13,
        idea:"Sin amor, los dones no valen nada: el amor es la señal más grande de una vida guiada por Dios.",
        preguntas:["¿Qué características del amor te cuesta más vivir?","¿A quién necesitas amar así esta semana?"] },
      { titulo:"Llenos del Espíritu", b:49, c:5, v1:15, v2:21,
        idea:"Pablo invita a vivir con sabiduría y a ser llenos del Espíritu, con gratitud y alabanza.",
        preguntas:["¿Qué señales acompañan a una vida llena del Espíritu?","¿Cómo puedes alimentar tu vida de adoración esta semana?"] },
    ],
  },
];

// ¿Dos pasajes se cruzan? (mismo libro y capítulo, y versículos que se solapan)
export function overlaps(a, b) {
  return a.b === b.b && a.c === b.c && a.v1 <= b.v2 && b.v1 <= a.v2;
}
